apiAndina/config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :products

  
  namespace :api do
    namespace :v1 do
      get 'out/getRfidInfo'
    end
  end

  namespace :api do
    namespace :v1 do
      get 'out/getStock'
    end
  end

  namespace :api do
    namespace :v1 do
      get 'out/getPointZona'
    end
  end

  namespace :api do
    namespace :v1 do
      get 'out/getZona'
      get 'out/getZonas'
    end
  end

  get 'home/index'

    ###################################################################### root ######################################################################
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

apiAndina/app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :product
end

apiAndina/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.paginate(:page => params[:page]) #.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:rfid, :product_id)
    end
end

apiAndina/app/helpers/tags_helper.rb
module TagsHelper
end

apiAndina/app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rfid %>
    <%= form.text_field :rfid, id: :tag_rfid %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, id: :tag_product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

apiAndina/app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

apiAndina/app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>
<%= will_paginate @tags %>


<table>
  <thead>
    <tr>
      <th>Rfid</th>
      <th>SKU</th>
      <th>Descripción</th>
      <th>Cajas x Pallets</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.rfid %></td>
        <td><%= tag.product.sku %></td>
        <td><%= tag.product.desc %></td>
        <td><%= tag.product.cjxpallet %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

apiAndina/app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

apiAndina/app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rfid:</strong>
  <%= @tag.rfid %>
</p>

<p>
  <strong>Product:</strong>
  <%= @tag.product %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>